name: App Infra Pipeline

on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [ main ]
permissions:
  id-token: write
  contents: read
jobs:
  dev:
    uses: seera-eswara/github-actions-templates/.github/workflows/terraform-iac.yml@v1.0.5
    with:
      environment: dev
      policy_repo: seera-eswara/terraform-policy-as-code
      working_directory: envs/dev
      policy_path: policies/definitions/
    secrets: inherit
    permissions:
      id-token: write
      contents: write
  prod:
    needs: dev
    uses: seera-eswara/github-actions-templates/.github/workflows/terraform-iac.yml@v1.0.5
    with:
      environment: prod
      policy_repo: seera-eswara/terraform-policy-as-code
      working_directory: envs/prod
      policy_path: policies/definitions/
    secrets: inherit
    permissions:
      id-token: write
      contents: read

